steps:
- id: "Pull Template"
  name: 'openfaas/faas-cli:latest-root'
  args: ['template', 'store', 'pull', golang-http]

- id: "Do a shrinkwrap build"
  name: 'openfaas/faas-cli:latest-root'
  args: ['build', '-f', './hello-world.yml', '--shrinkwrap']

- id: "Build the docker image"
  name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t=gcr.io/$PROJECT_ID/hello-world:$SHORT_SHA', '-t=gcr.io/$PROJECT_ID/hello-world:latest', '-f', './build/hello-world/Dockerfile', './build/hello-world/']

- id: "Push docker image"
  name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/$PROJECT_ID/hello-world:latest']

- id: "Login with faas-cli login"
  name: "openfaas/faas-cli:latest-root"
  entrypoint: "sh"
  args: ['-c', 'echo -n $${OPENFAAS_GATEWAY_PASSWD} | faas-cli login --password-stdin -g ${_GATEWAY}']
  secretEnv: ['OPENFAAS_GATEWAY_PASSWD']

- id: "Deploy to Openfaas"
  name: "openfaas/faas-cli:latest-root"
  args: ['deploy', '-f', './hello-world.yml', '-g', '${_GATEWAY}']

options:
  volumes:
    - name: 'buildvol'
      path: '/openfaas'

substitutions:
  _GATEWAY: http://34.68.185.231:8080

secrets:
- kmsKeyName: "projects/uts-1382/locations/global/keyRings/openfaas/cryptoKeys/openfaas-gateway-passwd"
  secretEnv:
    OPENFAAS_GATEWAY_PASSWD: "CiQAKhHBe0rvXk4gj5/GD69EzlchawsINVjVhk4nuj21JQUCS4MSUQCE45rqQ4wfIWUMgSyrOBOSUk+K1KBSVE4UKA7yK/ta6cjSc3wcEZT4siF/T3AxH4iLyRQvc0aI+yrySeVk1urZ2xlgNcfK38PpR9+dOYpuFw=="